### PR TITLE
fix for issue #4 "No files found to lint on Node.js project"

### PR DESCRIPTION
**Pull request by BitSchupser**
Hi,

I identified a race condition in the LintFactory that seems to be responsible for the problem described in issue #4 .

Furthermore I introduced the LongPath library (peteraritchie/LongPath @github) because under node_modules I had a path that was about 400 characters long. This caused an exception when calling Directory.Delete().

Greets and thank you for this awesum plugin.
Alex

### CODE REVIEW

**Comment by madskristensen** [comment]
A unit test failed.

Awesome catch on the mutex issue!!!

Adding the LongPath library isn't needed. The build script installs npm 3 which creates a flat structure. Please update your version of npm instead.

**Comment by madskristensen** [comment]
Unit test still fails. Can you run the unit tests locally in VS by opening in the Test Explorer tool window?

**Comment by BitSchupser** [comment]
When I run the tests locally, all tests are green. I have no idea what is the problem. Do you have any clue?
Am 14.12.2015 17:59 schrieb Mads Kristensen <notifications@github.com>:Unit test still fails. Can you run the unit tests locally in VS by opening in the Test Explorer tool window?

**Comment by madskristensen** [comment]
I'll try it locally. Thanks for the PR

**Pull request merged**
